networks:
  elk-net:

volumes:
  elk-backups_data: {}
  elk-elasticsearch_data: {}
  elk-etc-logstash_data: {}
  es8_data: {}

services:
  app:
  #    image: repo.sadad.co.ir/repository/oxygen-docker-group/elkmigration:0.0.8
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - elk2
      - elk8
    environment:
      - TZ=Asia/Tehran
  
      - APP_MONIGO_PORT=8080
      - APP_BULK_SIZE=10_000
      - APP_MAX_BULK_PAYLOAD_BYTES=104_857_600
      - APP_SCROLL_TTL=2m
      - APP_TTL=6s
      - APP_MAX_RETRIES=3
  
      # - ELK2_URLS=http://172.29.234.37:9201
      - ELK2_URLS=http://elk2:9200
      - ELK2_INDEX=oxygen
      - ELK2_USER=
      - ELK2_PASS=
      - ELK2_SORT_BY=started_at
      - ELK2_ASC=true

      # - ELK8_URLS=http://172.30.43.125:9200,http://172.30.43.126:9200,http://172.30.43.127:9200
      # - ELK8_INDEX=logs-generic-kong-kafka-log-plugin
      # - ELK8_USER=kngkafkausr
      # - ELK8_PASS=aTDRkbUWJUYTY%

      - ELK8_URLS=http://elk8:9200
      - ELK8_INDEX=oxygen
      - ELK8_USER=
      - ELK8_PASS=
      - ELK8_SORT_BY=started_at
      - ELK8_PASS=desc

     

    networks:
      - elk-net
    ports:
      - "8080:8080"
  
  elk2:
    image: sebp/elk:es241_l240_k461
    container_name: elk2
    ports:
      - "5602:5601"
      - "9202:9200"
      - "9301:9300"
      - "5045:5044"
      - "5001:5000"
    environment:
      - LOGSTASH_START=0
      - KIBANA_START=1
      - ELASTICSEARCH_START=1
    networks:
      - elk-net
    volumes:
      - elk-backups_data:/var/backups
      - elk-elasticsearch_data:/var/lib/elasticsearch
      - elk-etc-logstash_data:/etc/logstash


  elk8:
    image: elasticsearch:8.15.3
    container_name: elk8
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk-net
    ports:
      - "9208:9200"
    volumes:
      - es8_data:/usr/share/elasticsearch/data

  logstash:
    image: logstash:8.15.3
    container_name: logstash
    networks:
      - elk-net
    ports:
      - "5044:5044" # Beats input
      - "9600:9600" # Logstash monitoring API
    volumes:
      - ./.docker/logstash/pipeline:/usr/share/logstash/pipeline:ro
    depends_on:
      - elk8

  kibana_4_6_1:
    image: kibana:4.6.1
    container_name: kibana_4_6_1
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: "http://elk2:9200"
    networks:
      - elk-net

  kibana_latest:
    image: kibana:8.15.3
    container_name: kibana_8.15.3
    ports:
      - "5608:5601"
    environment:
      ELASTICSEARCH_URL: "http://elk8:9200"
    networks:
      - elk-net
