networks:
  elk-net:

volumes:
  elk-backups_data: {}
  elk-elasticsearch_data: {}
  elk-etc-logstash_data: {}

services:
  app:
#    image: elkmigration:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
      - elk2
      - elk8
    environment:
      - ELK_INDEX=${ELK_INDEX:-idx_elastic}

      - ELK2_URL=${ELK2_URL:-127.0.0.1:9202}
      - ELK2_USERNAME=${ELK2_USERNAME:-elastic}
      - ELK2_PASSWORD=${ELK2_PASSWORD:-changeme}

      - ELK7_URL=${ELK7_URL:-http://127.0.0.1:9207}
      - ELK7_USERNAME=${ELK7_USERNAME:-elastic}
      - ELK7_PASSWORD=${ELK7_PASSWORD:-changeme}

      - ELK8_URL=${ELK8_URL:-http://127.0.0.1:9208}
      - ELK8_USERNAME=${ELK8_USERNAME:-elastic}
      - ELK8_PASSWORD=${ELK8_PASSWORD:-changeme}

      - REDIS_URL=${REDIS_URL:-127.0.0.1:6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - REDIS_DB=${REDIS_DB:-0}
    networks:
      - elk-net

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    networks:
      - elk-net


  elk2:
    image: sebp/elk:es241_l240_k461
    container_name: elk2
    ports:
      - "5602:5601"
      - "9202:9200"
      - "9301:9300"
      - "5045:5044"
      - "5001:5000"
    environment:
      - LOGSTASH_START=0
      - KIBANA_START=1
      - ELASTICSEARCH_START=1
    networks:
      - elk-net
    volumes:
      - elk-backups_data:/var/backups
      - elk-elasticsearch_data:/var/lib/elasticsearch
      - elk-etc-logstash_data:/etc/logstash


  elk8:
    image: elasticsearch:8.15.3
    environment:
      - discovery.type=single-node
      - transport.host=127.0.0.1
      - network.host=0.0.0.0
    ports:
      - "9208:9200"
    networks:
      - elk-net