networks:
  elk-net:

volumes:
  elk-backups_data: {}
  elk-elasticsearch_data: {}
  elk-etc-logstash_data: {}
  es8_data: {}

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
      - elk2
      - elk8
    env_file:
      - .env.yaml
    networks:
      - elk-net
    ports:
      - "8080:8080"
    volumes:
      - ./logs/app.log:/logs/app.log
      - ./.env.yaml:/.env.yaml

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    networks:
      - elk-net


  elk2:
    image: sebp/elk:es241_l240_k461
    container_name: elk2
    ports:
      - "5602:5601"
      - "9202:9200"
      - "9301:9300"
      - "5045:5044"
      - "5001:5000"
    environment:
      - LOGSTASH_START=0
      - KIBANA_START=1
      - ELASTICSEARCH_START=1
    networks:
      - elk-net
    volumes:
      - elk-backups_data:/var/backups
      - elk-elasticsearch_data:/var/lib/elasticsearch
      - elk-etc-logstash_data:/etc/logstash


  elk8:
    image: elasticsearch:8.15.3
    container_name: elk8
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk-net
    ports:
      - "9208:9200"
    volumes:
      - es8_data:/usr/share/elasticsearch/data

  logstash:
    image: logstash:8.15.3
    container_name: logstash
    networks:
      - elk-net
    ports:
      - "5044:5044" # Beats input
      - "9600:9600" # Logstash monitoring API
    volumes:
      - ./.docker/logstash/pipeline:/usr/share/logstash/pipeline:ro
    depends_on:
      - elk8

  kibana_4_6_1:
    image: kibana:4.6.1
    container_name: kibana_4_6_1
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: "http://elk2:9200"
    networks:
      - elk-net

  kibana_latest:
    image: kibana:8.15.3
    container_name: kibana_8.15.3
    ports:
      - "5608:5601"
    environment:
      ELASTICSEARCH_URL: "http://elk8:9200"
    networks:
      - elk-net