input {
  beats {
    port => 5044
  }
}

filter {
  # Add filters as needed
}

output {
  elasticsearch {
    hosts => ["http://elk8:9200"]
    index => "logstash-%{+yyyy.MM.dd}"
  }
  stdout { codec => rubydebug }
}
